### ISSUE TITLE
Beachball of death

### ISSUE THREAD

**Issue by apuignav** [blaise-io/acelink#17]
Hi!

With 1.4.0, I get beachball of death when trying to open any acestream link, I get a beachball of death. Looking at the docker logs (Docker is updated to the latest version) I see the following

```
2020-01-19 20:06:09,240|MainThread|acestream|init segmenter failed
Traceback (most recent call last):
  File "core.c", line 333, in 
ImportError: cannot import name pysegmenter
2020-01-19 20:06:09,241|MainThread|acestream|platform=linux
2020-01-19 20:06:09,242|MainThread|acestream|app=acestream
2020-01-19 20:06:09,242|MainThread|acestream|version=3.1.49 code=3014900 revision=365f84f date=2019-07-11
2020-01-19 20:06:09,242|MainThread|acestream|use_local_db=True
2020-01-19 20:06:09,242|MainThread|acestream|use_m2crypto=True
2020-01-19 20:06:09,242|MainThread|acestream|is_gui_mode=0
2020-01-19 20:06:09,243|MainThread|acestream|enable debug: 0
2020-01-19 20:06:09,243|MainThread|acestream|get_default_api_version: 2
2020-01-19 20:06:09,243|MainThread|acestream.coreapp|use fixed i2i_port: 62062
2020-01-19 20:06:09,243|MainThread|acestream.coreapp|state_dir=u'/root/.ACEStream'
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
2020-01-19 20:06:09,351|MainThread|acestream.coreapp|set_debug_from_ui: level=0
2020-01-19 20:06:09,352|MainThread|acestream|enable debug: 0
2020-01-19 20:06:09,356|MainThread|acestream.coreapp|cannot load session config, use default
2020-01-19 20:06:09,376|MainThread|acestream.SocketHandler.InterruptSocket|bound on 127.0.0.1:53929
2020-01-19 20:06:09,376|MainThread|acestream.SocketHandler.SocketHandler|bind: socket bound: host=0.0.0.0 port=8621
2020-01-19 20:06:09,376|MainThread|acestream.LM|listen on 8621
2020-01-19 20:06:09,377|MainThread|acestream.localdb|No existing database found. Attempting to creating a new database u'/root/.ACEStream/sqlite/torrentstream.sdb'
2020-01-19 20:06:09,437|MainThread|acestream.VideoServer|start: addr= port=6878 allow_remote=0 allow_intranet=1
Exception in thread ZeroconfThread-21:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "ACEStream/third_party/zeroconf/zeroconf.py", line 849, in run
  File "ACEStream/third_party/zeroconf/zeroconf.py", line 1452, in _periodic_check
AttributeError: 'Zeroconf' object has no attribute 'last_sockets_check'
2020-01-19T20:06:09.934525519Z 
2020-01-19 20:06:09,938|ServiceTaskQueueThread-2|acestream.Session|sync_time: no response
2020-01-19 20:06:09,946|MainThread|acestream.SocketHandler.InterruptSocket|bound on 127.0.0.1:51879
2020-01-19 20:06:09,947|MainThread|acestream.SocketHandler.SocketHandler|bind: socket bound: host=0.0.0.0 port=62062
2020-01-19 20:06:09,948|Instance2InstanceThread-30|acestream.APIServer|run: ready to receive remote commands on 62062
```

I've cleaned the Docker cache (I think) but nothing seems to solve it. It was working a while back (can't say when this started happening, unfortunately). Any hints on how to solve it?

**Comment by blaise-io** [comment]
It seems like an issue with your Docker. Try restarting it.

Does `docker rmi blaiseio/acelink:1.4.0 && docker run --rm blaiseio/acelink:1.4.0` give you the same ImportError / AttributeError? (`ls: cannot access '/dev/disk/by-id/'` is expected).

You could also try completely resetting Docker. Only do this if you only use Docker for Ace Link (or know what you're doing): `docker system prune --all --volumes`

**Comment by lewisbilsland** [comment]
I've been getting the same issue on a new install of docker and acelink, I didn't sign up for a docker account, is this a requirement?

**Comment by blaise-io** [comment]
@lewisbilsland Signing up is not required. Are you on the latest Ace Link?

**Comment by lewisbilsland** [comment]
Installed docker manually with latest version of acelink

**Comment by alexreg** [comment]
I resolved this by manually starting Docker once before having AceLink start it. It would be nice for AceLink not to freeze up though, and at least show an error maybe (after a timeout?). :-)

**Comment by apuignav** [comment]
I did 

`docker rmi -f blaiseio/acelink:1.4.0 && docker run --rm blaiseio/acelink` 

and it fixed it for me!

**Comment by apuignav** [comment]
And just today, it came back again, and this doesn't work anymore:

```
$ docker rmi -f blaiseio/acelink:1.4.0 && docker run --rm blaiseio/acelink
Untagged: blaiseio/acelink:1.4.0
Untagged: blaiseio/acelink@sha256:a774346e0bd38e8041fa90d76f65db954af4810920f519edd965798eb73a77a4
Unable to find image 'blaiseio/acelink:latest' locally
latest: Pulling from blaiseio/acelink
804555ee0376: Pull complete
53c61c1a5043: Pull complete
34a71e49fa9f: Pull complete
f9a6a187567a: Pull complete
e63f8de0c028: Pull complete
3d69c2f3965c: Pull complete
edb4e39b60bb: Pull complete
89b0892be75f: Pull complete
Digest: sha256:a1baf3c3f19c3c4e9da20aaa5f8b4aa4fee6bcdb2670688c67e2ce6d87cad49f
Status: Downloaded newer image for blaiseio/acelink:latest
2020-02-09 20:34:26,657|MainThread|acestream|init segmenter failed
Traceback (most recent call last):
  File "core.c", line 333, in
ImportError: cannot import name pysegmenter
2020-02-09 20:34:26,660|MainThread|acestream|platform=linux
```

**Comment by acoks9** [comment]
Same issue here.

**Comment by blaise-io** [comment]
Can you try again on 1.5.0?

I should implement more logging and error handling to debug these kind of issues, as currently I have to guess what could go wrong (a lot) being on the same software (everything latest stable).

**Comment by acoks9** [comment]
```
docker rmi -f blaiseio/acelink:1.5.0
Untagged: blaiseio/acelink:1.5.0
Untagged: blaiseio/acelink@sha256:b2bb880af45b81daad9ad668aa215d54391b3786b94a486bd7382931af02ca2e
Deleted: sha256:b8073ed41ca74b4b78d85da0292d801712e5ee746878d96acd2591716faaff27
Deleted: sha256:5ce1d197d794dd7a175cbeeefb08ab2dec58e4ace917edbde9e2abdf3e2a3561
Deleted: sha256:fefd78775882474e8c687faadc571c07f837f178432afb50ae00eabf972751a0
Deleted: sha256:c67187df6c3ca9951e7e1bbdbcd0f686352dd339c57c8e3bc92d2f196f3feb39
Deleted: sha256:bfc9823e727784044812d01a461317808a40193799fabc5835e65441d95323eb
Deleted: sha256:46f9674c55c7b6a705d58a042a9b1fbf9e6487c8ec1f8581de5d7e92d22eb480
Deleted: sha256:66eac46e76d40dbe1cd17626516828f44fe36e887df901ced8cd124e63aa2691
Deleted: sha256:cad1658633c9d2036d9ebbf10451970c73ddcd17ddd6b6e518ecfa8c239384c5
Deleted: sha256:4a38308ef55d68ec61916a4f64d50d839cc9d814d79060bf358e08269ec0c9dc
Deleted: sha256:e0db3ba0aaea8a01d5cb000aeb449c153be0a47a369cafc4e912b85fb18192cf
docker run --rm blaiseio/acelink
Unable to find image 'blaiseio/acelink:latest' locally
latest: Pulling from blaiseio/acelink
619014d83c02: Pull complete 
e28b3882d923: Pull complete 
0938940c4aca: Pull complete 
1407d3158cbc: Pull complete 
2c10ab898a36: Pull complete 
7f35aa072372: Pull complete 
1acbc2603558: Pull complete 
b9266d3c4e03: Pull complete 
4dc9db873110: Pull complete 
Digest: sha256:762496dbfb144ac1c0c82a6c277850eecc5f7db0b0a635dabc660982bb5cd47f
Status: Downloaded newer image for blaiseio/acelink:latest
2020-02-15 12:39:16,778|MainThread|acestream|init segmenter failed
Traceback (most recent call last):
  File "core.c", line 333, in 
ImportError: cannot import name pysegmenter
2020-02-15 12:39:16,778|MainThread|acestream|platform=linux
2020-02-15 12:39:16,779|MainThread|acestream|app=acestream
2020-02-15 12:39:16,780|MainThread|acestream|version=3.1.49 code=3014900 revision=365f84f date=2019-07-11
2020-02-15 12:39:16,780|MainThread|acestream|use_local_db=True
2020-02-15 12:39:16,780|MainThread|acestream|use_m2crypto=True
2020-02-15 12:39:16,780|MainThread|acestream|is_gui_mode=0
2020-02-15 12:39:16,781|MainThread|acestream|enable debug: 0
2020-02-15 12:39:16,782|MainThread|acestream|get_default_api_version: 2
2020-02-15 12:39:16,782|MainThread|acestream.coreapp|use fixed i2i_port: 62062
2020-02-15 12:39:16,782|MainThread|acestream.coreapp|state_dir=u'/root/.ACEStream'
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
2020-02-15 12:39:16,904|MainThread|acestream.coreapp|set_debug_from_ui: level=0
2020-02-15 12:39:16,905|MainThread|acestream|enable debug: 0
2020-02-15 12:39:16,910|MainThread|acestream.coreapp|cannot load session config, use default
2020-02-15 12:39:16,932|MainThread|acestream.SocketHandler.InterruptSocket|bound on 127.0.0.1:50665
2020-02-15 12:39:16,932|MainThread|acestream.SocketHandler.SocketHandler|bind: socket bound: host=0.0.0.0 port=8621
2020-02-15 12:39:16,932|MainThread|acestream.LM|listen on 8621
2020-02-15 12:39:18,047|MainThread|acestream.VideoServer|start: addr= port=6878 allow_remote=0 allow_intranet=1
2020-02-15 12:39:18,282|ServiceTaskQueueThread-2|acestream.Session|sync_time: no response
2020-02-15 12:39:18,287|MainThread|acestream.SocketHandler.InterruptSocket|bound on 127.0.0.1:46298
2020-02-15 12:39:18,289|MainThread|acestream.SocketHandler.SocketHandler|bind: socket bound: host=0.0.0.0 port=62062
2020-02-15 12:39:18,290|Instance2InstanceThread-30|acestream.APIServer|run: ready to receive remote commands on 62062
```

**Comment by stianfp** [comment]
Get the same issue here, with latest version 1.5.0.

**Comment by blaise-io** [comment]
Please update to 1.6.0, open Console.app to view logs, open a stream in Ace Link, filter logs by Ace Link in Console.app, and paste those here. 

Please remove any stream hashes form the logs before posting.

**Comment by blaise-io** [comment]
Closed because of inactivity.

**Comment by markholland** [comment]
Console.app

```
default	13:28:19.256161+0200	Ace Link	Open stream
default	13:28:19.258677+0200	Ace Link	<private> Docker image: blaiseio/acelink:1.6.0
Acestream hash: [HASH-REDACTED]
default	13:28:19.296871+0200	Ace Link	<private> Docker is running
default	13:28:19.368603+0200	Ace Link	<private> Starting Ace Stream server
default	13:28:20.686789+0200	Ace Link	<private>
default	13:28:20.686831+0200	Ace Link	<private> Ace Stream server is running
Verifying stream: http://127.0.0.1:6878/ace/getstream?id=[HASH-REDACTED]
default	13:28:21.160350+0200	Ace Link	<private> Redirect to http://127.0.0.1:6878/ace/r/a5d63d83ed94f97c2f1d958b4d32cfdf34811149/1b5337d0c8ad813197b506146d8d503d
default	13:28:21.161029+0200	Ace Link	<private> Retrieving title
default	13:28:21.280435+0200	Ace Link	<private> Title: [REDACTED]
Creating playlist
default	13:28:21.282119+0200	Ace Link	<private> Opening stream http://127.0.0.1:6878/ace/getstream?id=[HASH-REDACTED] from /Users/[USER-REDACTED]/Library/Application Support/Ace Link/streams/[REDACTED] [a30c60f].m3u8
default	13:28:21.321947+0200	tccd	-[TCCDAccessIdentity staticCode]: static code for: identifier blaise.io.acelink, type: 0: 0x7faba7f1e180 at /Applications/Ace Link.app
default	13:28:21.387104+0200	Ace Link	<private> ran successfully
default	13:28:28.072981+0200	Ace Link	LSExceptions shared instance invalidated for timeout.
default	13:29:00.569924+0200	Ace Link	Connection 1: is being canceled
default	13:29:00.569966+0200	Ace Link	[C1 DF8155DC-0083-4951-BF9C-E8CAB33C16E4 Hostname#0d0eb6ee:443 tcp, url hash: 11fca06a, tls] cancel
default	13:29:00.570039+0200	Ace Link	[C1 DF8155DC-0083-4951-BF9C-E8CAB33C16E4 Hostname#0d0eb6ee:443 tcp, url hash: 11fca06a, tls] cancelled
	[C1.1 10CEB67B-7AE5-4428-AC36-8501A23BB64E 192.168.1.105:50630<->IPv4#eb389089:443]
	Connected Path: satisfied (Path is satisfied), interface: en0, ipv4, dns
	Duration: 60.120s, DNS @0.000s took 0.001s, TCP @0.002s took 0.044s, TLS took 0.073s
	bytes in/out: 4825/950, packets in/out: 6/3, rtt: 0.049s, retransmitted packets: 0, out-of-order packets: 0
default	13:29:00.570061+0200	Ace Link	0.000s [C1 2268B81C-3574-455A-89AA-6D6DAA9B7AE0 Hostname#0d0eb6ee:443 resolver path=satisfied (Path is satisfied), interface: en0, ipv4, dns] path:start
default	13:29:00.570075+0200	Ace Link	0.000s [C1 2268B81C-3574-455A-89AA-6D6DAA9B7AE0 Hostname#0d0eb6ee:443 resolver path=satisfied (Path is satisfied), interface: en0, ipv4, dns] path:satisfied
default	13:29:00.570087+0200	Ace Link	0.000s [C1 2268B81C-3574-455A-89AA-6D6DAA9B7AE0 Hostname#0d0eb6ee:443 resolver path=satisfied (Path is satisfied), interface: en0, ipv4, dns] resolver:start_dns
default	13:29:00.570099+0200	Ace Link	0.001s [C1 2268B81C-3574-455A-89AA-6D6DAA9B7AE0 Hostname#0d0eb6ee:443 resolver path=satisfied (Path is satisfied), interface: en0, ipv4, dns] resolver:receive_dns
default	13:29:00.570112+0200	Ace Link	0.001s [C1.1 10CEB67B-7AE5-4428-AC36-8501A23BB64E 192.168.1.105:50630<->IPv4#eb389089:443 socket-flow path=satisfied (Path is satisfied), interface: en0, ipv4, dns] path:start
default	13:29:00.570126+0200	Ace Link	0.001s [C1.1 10CEB67B-7AE5-4428-AC36-8501A23BB64E 192.168.1.105:50630<->IPv4#eb389089:443 socket-flow path=satisfied (Path is satisfied), interface: en0, ipv4, dns] path:satisfied
default	13:29:00.570137+0200	Ace Link	0.002s [C1.1 10CEB67B-7AE5-4428-AC36-8501A23BB64E 192.168.1.105:50630<->IPv4#eb389089:443 socket-flow path=satisfied (Path is satisfied), interface: en0, ipv4, dns] flow:start_connect
default	13:29:00.570148+0200	Ace Link	0.035s [C1 2268B81C-3574-455A-89AA-6D6DAA9B7AE0 Hostname#0d0eb6ee:443 resolver path=satisfied (Path is satisfied), interface: en0, ipv4, dns] resolver:receive_dns
default	13:29:00.570162+0200	Ace Link	0.046s [C1.1 10CEB67B-7AE5-4428-AC36-8501A23BB64E 192.168.1.105:50630<->IPv4#eb389089:443 socket-flow path=satisfied (Path is satisfied), interface: en0, ipv4, dns] flow:finish_transport
default	13:29:00.570173+0200	Ace Link	0.046s [C1 2268B81C-3574-455A-89AA-6D6DAA9B7AE0 Hostname#0d0eb6ee:443 resolver path=satisfied (Path is satisfied), interface: en0, ipv4, dns] flow:finish_transport
default	13:29:00.570184+0200	Ace Link	0.119s [C1.1 10CEB67B-7AE5-4428-AC36-8501A23BB64E 192.168.1.105:50630<->IPv4#eb389089:443 socket-flow path=satisfied (Path is satisfied), interface: en0, ipv4, dns] flow:finish_connect
default	13:29:00.570195+0200	Ace Link	0.119s [C1 2268B81C-3574-455A-89AA-6D6DAA9B7AE0 Hostname#0d0eb6ee:443 resolver path=satisfied (Path is satisfied), interface: en0, ipv4, dns] flow:finish_connect
default	13:29:00.570231+0200	Ace Link	0.119s [C1.1 10CEB67B-7AE5-4428-AC36-8501A23BB64E 192.168.1.105:50630<->IPv4#eb389089:443 socket-flow path=satisfied (Path is satisfied), interface: en0, ipv4, dns] flow:changed_viability
default	13:29:00.570250+0200	Ace Link	0.119s [C1 2268B81C-3574-455A-89AA-6D6DAA9B7AE0 Hostname#0d0eb6ee:443 resolver path=satisfied (Path is satisfied), interface: en0, ipv4, dns] flow:changed_viability
default	13:29:00.570275+0200	Ace Link	60.120s [C1] path:cancel
default	13:29:00.570485+0200	Ace Link	boringssl_context_message_handler(2258) [C1.1:2][0x7ff1fc607f00] Writing SSL3_RT_ALERT 2 bytes
default	13:29:00.570504+0200	Ace Link	boringssl_context_handle_warning_alert(1893) [C1.1:2][0x7ff1fc607f00] write alert, level: warning, description: close notify
default	13:29:00.570522+0200	Ace Link	boringssl_session_disconnect(504) [C1.1:2][0x7ff1fc607f00] SSL_shutdown 0
default	13:29:00.570533+0200	Ace Link	nw_flow_disconnected [C1.1 IPv4#eb389089:443 cancelled socket-flow ((null))] Output protocol disconnected
default	13:29:00.570602+0200	Ace Link	nw_connection_report_state_with_handler_on_nw_queue [C1] reporting state cancelled
default	13:29:00.570838+0200	Ace Link	Connection 1: destroyed
default	13:29:00.570858+0200	Ace Link	nw_protocol_boringssl_remove_input_handler(1012) [C1.1:2][0x7ff1fc607f00] nw_protocol_boringssl_remove_input_handler forced true
default	13:29:00.570878+0200	Ace Link	nw_protocol_boringssl_remove_input_handler(1030) [C1.1:2][0x7ff1fc607f00] Transferring nw_protocol_boringssl_t handle back into ARC for autorelease
```

Docker logs

```
2020-07-30 11:28:20,137|MainThread|acestream|init segmenter failed
Traceback (most recent call last):
  File "core.c", line 333, in
ImportError: cannot import name pysegmenter
2020-07-30 11:28:20,138|MainThread|acestream|platform=linux
2020-07-30 11:28:20,139|MainThread|acestream|app=acestream
2020-07-30 11:28:20,139|MainThread|acestream|version=3.1.49 code=3014900 revision=365f84f date=2019-07-11
2020-07-30 11:28:20,139|MainThread|acestream|use_local_db=True
2020-07-30 11:28:20,139|MainThread|acestream|use_m2crypto=True
2020-07-30 11:28:20,139|MainThread|acestream|is_gui_mode=0
2020-07-30 11:28:20,139|MainThread|acestream|enable debug: 0
2020-07-30 11:28:20,141|MainThread|acestream|get_default_api_version: 2
2020-07-30 11:28:20,141|MainThread|acestream.coreapp|use fixed i2i_port: 62062
2020-07-30 11:28:20,141|MainThread|acestream.coreapp|state_dir=u'/root/.ACEStream'
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
2020-07-30 11:28:20,216|MainThread|acestream.coreapp|set_debug_from_ui: level=0
2020-07-30 11:28:20,217|MainThread|acestream|enable debug: 0
2020-07-30 11:28:20,221|MainThread|acestream.coreapp|cannot load session config, use default
2020-07-30 11:28:20,236|MainThread|acestream.SocketHandler.InterruptSocket|bound on 127.0.0.1:59918
2020-07-30 11:28:20,236|MainThread|acestream.SocketHandler.SocketHandler|bind: socket bound: host=0.0.0.0 port=8621
2020-07-30 11:28:20,237|MainThread|acestream.LM|listen on 8621
2020-07-30 11:28:20,266|MainThread|acestream.VideoServer|start: addr= port=6878 allow_remote=0 allow_intranet=1
2020-07-30 11:28:20,452|ServiceTaskQueueThread-2|acestream.Session|sync_time: no response
2020-07-30 11:28:20,455|MainThread|acestream.SocketHandler.InterruptSocket|bound on 127.0.0.1:38094
2020-07-30 11:28:20,456|MainThread|acestream.SocketHandler.SocketHandler|bind: socket bound: host=0.0.0.0 port=62062
2020-07-30 11:28:20,456|Instance2InstanceThread-30|acestream.APIServer|run: ready to receive remote commands on 62062
```

**Comment by AndreMPCosta** [comment]
```
docker run --platform linux/amd64 --rm blaiseio/acelink     
Unable to find image 'blaiseio/acelink:latest' locally
latest: Pulling from blaiseio/acelink
75cb2ebf3b3c: Already exists 
891774e886a1: Pull complete 
abfa783ab0f4: Pull complete 
c820a8cda59d: Pull complete 
29edae61a53e: Pull complete 
1e447a8b6920: Pull complete 
e917ea098e1b: Pull complete 
8b2d525c398f: Pull complete 
ed905f98e029: Pull complete 
Digest: sha256:c5975e48692bd189563284f4405c889ac9e430bac69300ab929d3b44eebe58fb
Status: Downloaded newer image for blaiseio/acelink:latest
2021-01-02 19:55:48,427|MainThread|acestream|init segmenter failed
Traceback (most recent call last):
  File "core.c", line 333, in 
ImportError: cannot import name pysegmenter
2021-01-02 19:55:48,429|MainThread|acestream|platform=linux
2021-01-02 19:55:48,432|MainThread|acestream|app=acestream
2021-01-02 19:55:48,432|MainThread|acestream|version=3.1.49 code=3014900 revision=365f84f date=2019-07-11
2021-01-02 19:55:48,433|MainThread|acestream|use_local_db=True
2021-01-02 19:55:48,433|MainThread|acestream|use_m2crypto=True
2021-01-02 19:55:48,434|MainThread|acestream|is_gui_mode=0
2021-01-02 19:55:48,435|MainThread|acestream|enable debug: 0
2021-01-02 19:55:48,446|MainThread|acestream|get_default_api_version: 2
2021-01-02 19:55:48,446|MainThread|acestream.coreapp|use fixed i2i_port: 62062
2021-01-02 19:55:48,447|MainThread|acestream.coreapp|state_dir=u'/root/.ACEStream'
/bin/ls: cannot access '/dev/disk/by-id/': No such file or directory
/bin/ls: cannot access '/dev/disk/by-id/': No such file or directory
/bin/ls: cannot access '/dev/disk/by-id/': No such file or directory
/bin/ls: cannot access '/dev/disk/by-id/': No such file or directory
/bin/ls: cannot access '/dev/disk/by-id/': No such file or directory
/bin/ls: cannot access '/dev/disk/by-id/': No such file or directory
/bin/ls: cannot access '/dev/disk/by-id/': No such file or directory
/bin/ls: cannot access '/dev/disk/by-id/': No such file or directory
/bin/ls: cannot access '/dev/disk/by-id/': No such file or directory
/bin/ls: cannot access '/dev/disk/by-id/': No such file or directory
/bin/ls: cannot access '/dev/disk/by-id/': No such file or directory
/bin/ls: cannot access '/dev/disk/by-id/': No such file or directory
/bin/ls: cannot access '/dev/disk/by-id/': No such file or directory
/bin/ls: cannot access '/dev/disk/by-id/': No such file or directory
/bin/ls: cannot access '/dev/disk/by-id/': No such file or directory
/bin/ls: cannot access '/dev/disk/by-id/': No such file or directory
/bin/ls: cannot access '/dev/disk/by-id/': No such file or directory
/bin/ls: cannot access '/dev/disk/by-id/': No such file or directory
/bin/ls: cannot access '/dev/disk/by-id/': No such file or directory
/bin/ls: cannot access '/dev/disk/by-id/': No such file or directory
/bin/ls: cannot access '/dev/disk/by-id/': No such file or directory
/bin/ls: cannot access '/dev/disk/by-id/': No such file or directory
/bin/ls: cannot access '/dev/disk/by-id/': No such file or directory
/bin/ls: cannot access '/dev/disk/by-id/': No such file or directory
/bin/ls: cannot access '/dev/disk/by-id/': No such file or directory
/bin/ls: cannot access '/dev/disk/by-id/': No such file or directory
2021-01-02 19:55:49,324|MainThread|acestream.coreapp|set_debug_from_ui: level=0
2021-01-02 19:55:49,328|MainThread|acestream|enable debug: 0
2021-01-02 19:55:49,367|MainThread|acestream.coreapp|cannot load session config, use default
: error fetching interface information: Device not found
2021-01-02 19:55:49,511|MainThread|acestream.SocketHandler.InterruptSocket|bound on 127.0.0.1:51059
2021-01-02 19:55:49,512|MainThread|acestream.SocketHandler.SocketHandler|bind: socket bound: host=0.0.0.0 port=8621
2021-01-02 19:55:49,512|MainThread|acestream.LM|listen on 8621
2021-01-02 19:55:49,648|AceStreamCoreThread|acestream.SocketHandler.SocketHandler|create_multicast_sockets: failed to create socket: ip=239.255.17.18 port=32968 local=172.17.0.4
Traceback (most recent call last):
  File "ACEStream/Core/BitTornado/SocketHandler.py", line 842, in create_multicast_sockets
  File "ACEStream/Core/BitTornado/SocketHandler.py", line 860, in create_single_multicast_socket
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 92] Protocol not available
2021-01-02 19:55:49,663|MainThread|acestream.VideoServer|start: addr= port=6878 allow_remote=0 allow_intranet=1
2021-01-02 19:55:50,423|MainThread|acestream.coreapp|failed to start aircast manager
Traceback (most recent call last):
  File "core.c", line 1483, in 
  File "core.c", line 122, in 
  File "core.c", line 290, in 
  File "ACEStream/third_party/zeroconf/zeroconf.py", line 1400, in __init__
  File "ACEStream/third_party/zeroconf/zeroconf.py", line 1437, in _init_sockets
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 92] Protocol not available
2021-01-02 19:55:50,431|ServiceTaskQueueThread-2|acestream.Session|sync_time: no response
2021-01-02 19:55:50,459|MainThread|acestream.SocketHandler.InterruptSocket|bound on 127.0.0.1:55673
2021-01-02 19:55:50,460|MainThread|acestream.SocketHandler.SocketHandler|bind: socket bound: host=0.0.0.0 port=62062
2021-01-02 19:55:50,461|Instance2InstanceThread-29|acestream.APIServer|run: ready to receive remote commands on 62062
Exception in thread ZeroconfThread-21:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "ACEStream/third_party/zeroconf/zeroconf.py", line 849, in run
  File "ACEStream/third_party/zeroconf/zeroconf.py", line 1452, in _periodic_check
AttributeError: 'Zeroconf' object has no attribute 'last_sockets_check'

2021-01-02 19:56:20,501|TrafficStatsSenderThread|acestream.TrafficStatsSender|init: error: <urlopen error timed out>
2021-01-02 19:56:22,475|MainThread|acestream|failed to report error
Traceback (most recent call last):
  File "core.c", line 352, in 
  File "core.c", line 10334, in 
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 110] Connection timed out>
```

I'm also having problems running this.
