### ISSUE TITLE
Ace Link Error (Code 103)

### ISSUE THREAD

**Issue by gondeleon** [blaise-io/acelink#25]
Hello, I have a problem when trying to open an acestream:// link from [website] that directly open the stream in VLC.
Error Code 103 pops-up three times.
When I copy the link like this on the clipboard it works perfectly.

Thanks!

**Comment by blaise-io** [comment]
Might be a coincidence? I can directly open acestream:// links in Ace Link from Safari, Chrome and Firefox. 
Can you try again with another stream?

**Comment by gmoreno229** [comment]
Hi thanks for your efforts on this helpful forum. 

I found this open issue because I was having the same issue. The only difference is the website where I used to get acestreams from is broadcasting through a kind of flash player now (no running) so acestream links are no longer visible. The only link which is on the page says to click it to run "ACEPLAYER" and after clicking a ace link error on my mac like gondelon user one appears.I don't see the way to copy the link and run it directly from ace link. 

My question is, Is there any way to get the acestream link from a website like this to play it on ace link? 

Many thanks in advance for your help!

**Comment by gondeleon** [comment]
Sorry I forgot to answer!
There isn't a problem when copying the link to Ace Link, this way works fine.
The problem is as gmoreno229 stated, no links available only using the flash player or trying to open it with VLC.
It does work with Windows though.
Thanks for you work!

**Comment by danielb7390** [comment]
@gmoreno229  i think we are talking about the same website, if you check the network requests while pressing play you can find this  
 `http://127.0.0.1:6878/ace/manifest.m3u8?url=https://cdn.thatwebsite.something/channelnumber.m3u8`
This url makes sense, it's trying to connect to the local ace engine, but instead of a acestream hash the url gives a `.acelive` file
Anyways, i didn't manage to make it to work, got  a bunch of errors in the logs, not sure if the channel was down, my vpn was acting up, or if it's just a random error
```
2020-09-18 19:13:41,814|MainThread|acestream|platform=linux
2020-09-18 19:13:41,814|MainThread|acestream|app=acestream
2020-09-18 19:13:41,814|MainThread|acestream|version=3.1.49 code=3014900 revision=365f84f date=2019-07-11
2020-09-18 19:13:41,814|MainThread|acestream|use_local_db=True
2020-09-18 19:13:41,815|MainThread|acestream|use_m2crypto=True
2020-09-18 19:13:41,815|MainThread|acestream|is_gui_mode=0
2020-09-18 19:13:41,815|MainThread|acestream|enable debug: 0
2020-09-18 19:13:41,815|MainThread|acestream|get_default_api_version: 2
2020-09-18 19:13:41,815|MainThread|acestream.coreapp|use fixed i2i_port: 62062
2020-09-18 19:13:41,815|MainThread|acestream.coreapp|state_dir=u'/root/.ACEStream'
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
ls: cannot access '/dev/disk/by-id/': No such file or directory
2020-09-18 19:13:41,865|MainThread|acestream.coreapp|set_debug_from_ui: level=0
2020-09-18 19:13:41,866|MainThread|acestream|enable debug: 0
2020-09-18 19:13:41,870|MainThread|acestream.coreapp|cannot load session config, use default
2020-09-18 19:13:41,882|MainThread|acestream.SocketHandler.InterruptSocket|bound on 127.0.0.1:50065
2020-09-18 19:13:41,882|MainThread|acestream.SocketHandler.SocketHandler|bind: socket bound: host=0.0.0.0 port=8621
2020-09-18 19:13:41,883|MainThread|acestream.LM|listen on 8621
2020-09-18 19:13:41,916|MainThread|acestream.VideoServer|start: addr= port=6878 allow_remote=0 allow_intranet=1
2020-09-18 19:13:42,108|ServiceBrowserThread-23|zc|run: got socket error
2020-09-18 19:13:42,110|ServiceTaskQueueThread-2|acestream.Session|sync_time: no response
2020-09-18 19:13:42,110|MainThread|acestream.SocketHandler.InterruptSocket|bound on 127.0.0.1:40324
2020-09-18 19:13:42,111|MainThread|acestream.SocketHandler.SocketHandler|bind: socket bound: host=0.0.0.0 port=62062
2020-09-18 19:13:42,112|Instance2InstanceThread-30|acestream.APIServer|run: ready to receive remote commands on 62062
2020-09-18 19:13:42,607|ServiceBrowserThread-23|zc|run: got socket error
2020-09-18 19:13:44,568|ServiceBrowserThread-23|zc|run: got socket error
2020-09-18 19:13:46,568|ServiceBrowserThread-23|zc|run: got socket error
2020-09-18 19:13:50,568|ServiceBrowserThread-23|zc|run: got socket error
2020-09-18 19:13:58,568|ServiceBrowserThread-23|zc|run: got socket error
2020-09-18 19:14:14,569|ServiceBrowserThread-23|zc|run: got socket error
2020-09-18 19:14:34,569|ServiceBrowserThread-23|zc|run: got socket error
2020-09-18 19:14:54,569|ServiceBrowserThread-23|zc|run: got socket error
2020-09-18 19:15:14,569|ServiceBrowserThread-23|zc|run: got socket error
2020-09-18 19:15:32,915|AceStreamCoreThread|acestream.live.download.xxxxxxxxxxxxxxxxxxxxxxx|send_multicast_pex_announce: error
Traceback (most recent call last):
File "core.c", line 1449, in
File "ACEStream/Core/APIImplementation/LiveDownloadImpl.py", line 594, in send_multicast
File "ACEStream/Core/APIImplementation/LaunchManyCore.py", line 1162, in send_multicast
error: [Errno 1] Operation not permitted
2020-09-18 19:15:33,509|SegmenterThread-49|acestream.ProxyTransporter|segmenter_thread_func: error
Traceback (most recent call last):
File "core.c", line 942, in
ImportError: cannot import name pysegmenter
2020-09-18 19:15:34,569|ServiceBrowserThread-23|zc|run: got socket error
2020-09-18 19:15:54,569|ServiceBrowserThread-23|zc|run: got socket error
2020-09-18 19:16:14,570|ServiceBrowserThread-23|zc|run: got socket error
2020-09-18 19:16:34,570|ServiceBrowserThread-23|zc|run: got socket error
2020-09-18 19:16:54,570|ServiceBrowserThread-23|zc|run: got socket error
2020-09-18 19:17:14,570|ServiceBrowserThread-23|zc|run: got socket error
2020-09-18 19:17:34,570|ServiceBrowserThread-23|zc|run: got socket error
2020-09-18 19:17:54,570|ServiceBrowserThread-23|zc|run: got socket error
```

**Comment by gmoreno229** [comment]
Hi thanks for your feedback. Before keep going just to make sure, are we allowed to mention other websites with illegal content? I wouldn't put in a problem anyone @blaise-io

**Comment by blaise-io** [comment]
@gmoreno229 please don't post any (websites with) streams containing copyrighted content. If you want me to debug a specific stream, please email to blaisekal@gmail.com.

**Comment by danielb7390** [comment]
@blaise-io just sent you an email with some information. I won't be able to help more since i no longer use acestreams.

**Comment by blaise-io** [comment]
@gmoreno229 @danielb7390 I don't know yet why it doesn't work with this website, I tried many things.

Workaround: on a video page, open the browser web developer console (F12) and paste the following in the Console tab: 

```location.href = `acestream://${(new URL(player.options.source)).searchParams.get('id')}`;```

**Comment by z0mb1ek** [comment]
same error with streams, cannot get manifest.m3u8 with error ```failed to load transport file```

**Comment by prodigel** [comment]
Just in case someone follows this thread give the following 'hack' a try:
- go to /Applications/Ace Link.app/Contents/Resources
- edit Dockerfile and comment out the sqlite3 line (# on the start of the line)
- remove any existing blaiseio/acelink images/containers from Docker dashboard

It worked for me ;)
I'm not experienced enough to fix it, but from reading posts on the Internetz it seems that a newer version of sqlite messed up the base image libraries. Funny part is sqlite3 is not even necessary it seems ... 🤔

**Comment by blaise-io** [comment]
﻿SQLite is installed to read the stream title from Acestream's internal database. I doubt SQLite is the source of the issue, more likely any rebuild of the image is fixing the issue for you.

**Comment by blaise-io** [comment]
Websites launching `acestream://`, then communicate with the server directly is fixed in https://github.com/blaise-io/acelink/releases/tag/1.7.0.
