### ISSUE TITLE
Ace Link not working with Private Relay

### ISSUE THREAD

**Issue by alikhanoitan** [blaise-io/acelink#40]
**Describe the bug**  
…  
I tried many different ace stream links, and all of them failed to load. They crash differently, but mostly leave the logs as below.
Note: Don't share Acestream IDs or websites containing pirated content.

**What I expected to happen**  
…

**Screenshots**  
…

**Additional debug info**  
…
```
2021-10-24 18:48:21,301|MainThread|acestream|init segmenter failed

Traceback (most recent call last):

  File "core.c", line 333, in 

ImportError: cannot import name pysegmenter

2021-10-24 18:48:21,302|MainThread|acestream|platform=linux

2021-10-24 18:48:21,303|MainThread|acestream|app=acestream

2021-10-24 18:48:21,303|MainThread|acestream|version=3.1.49 code=3014900 revision=365f84f date=2019-07-11

2021-10-24 18:48:21,303|MainThread|acestream|use_local_db=True

2021-10-24 18:48:21,304|MainThread|acestream|use_m2crypto=True

2021-10-24 18:48:21,304|MainThread|acestream|is_gui_mode=0

2021-10-24 18:48:21,304|MainThread|acestream|enable debug: 0

2021-10-24 18:48:21,305|MainThread|acestream|get_default_api_version: 2

2021-10-24 18:48:21,305|MainThread|acestream.coreapp|use fixed i2i_port: 62062

2021-10-24 18:48:21,306|MainThread|acestream.coreapp|state_dir=u'/root/.ACEStream'

2021-10-24 18:48:21,488|MainThread|acestream.coreapp|set_debug_from_ui: level=0

2021-10-24 18:48:21,489|MainThread|acestream|enable debug: 0

2021-10-24 18:48:21,496|MainThread|acestream.coreapp|cannot load session config, use default

2021-10-24 18:48:21,520|MainThread|acestream.SocketHandler.InterruptSocket|bound on 127.0.0.1:50195

2021-10-24 18:48:21,520|MainThread|acestream.SocketHandler.SocketHandler|bind: socket bound: host=0.0.0.0 port=8621

2021-10-24 18:48:21,520|MainThread|acestream.LM|listen on 8621

2021-10-24 18:48:21,521|MainThread|acestream.localdb|No existing database found. Attempting to creating a new database u'/root/.ACEStream/sqlite/torrentstream.sdb'

2021-10-24 18:48:21,569|MainThread|acestream.VideoServer|start: addr= port=6878 allow_remote=1 allow_intranet=1

2021-10-24 18:48:21,975|ServiceTaskQueueThread-2|acestream.Session|sync_time: no response

2021-10-24 18:48:21,981|MainThread|acestream.SocketHandler.InterruptSocket|bound on 127.0.0.1:53383

2021-10-24 18:48:21,983|MainThread|acestream.SocketHandler.SocketHandler|bind: socket bound: host=0.0.0.0 port=62062

2021-10-24 18:48:21,984|Instance2InstanceThread-33|acestream.APIServer|run: ready to receive remote commands on 62062

2021-10-24 18:48:32,006|TrafficStatsSenderThread|acestream.TrafficStatsSender|init: error: <urlopen error timed out>

2021-10-24 18:48:37,814|MainThread|acestream|failed to report error

Traceback (most recent call last):

  File "core.c", line 352, in 

  File "core.c", line 10334, in 

  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen

    return opener.open(url, data, timeout)

  File "/usr/lib/python2.7/urllib2.py", line 429, in open

    response = self._open(req, data)

  File "/usr/lib/python2.7/urllib2.py", line 447, in _open

    '_open', req)

  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain

    result = func(*args)

  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open

    return self.do_open(httplib.HTTPConnection, req)

  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open

    raise URLError(err)

URLError: <urlopen error [Errno 113] No route to host>

ls: cannot access '/dev/disk/by-id/': No such file or directory

ls: cannot access '/dev/disk/by-id/': No such file or directory

ls: cannot access '/dev/disk/by-id/': No such file or directory

ls: cannot access '/dev/disk/by-id/': No such file or directory

ls: cannot access '/dev/disk/by-id/': No such file or directory

ls: cannot access '/dev/disk/by-id/': No such file or directory

ls: cannot access '/dev/disk/by-id/': No such file or directory

ls: cannot access '/dev/disk/by-id/': No such file or directory

ls: cannot access '/dev/disk/by-id/': No such file or directory

ls: cannot access '/dev/disk/by-id/': No such file or directory

ls: cannot access '/dev/disk/by-id/': No such file or directory

ls: cannot access '/dev/disk/by-id/': No such file or directory

ls: cannot access '/dev/disk/by-id/': No such file or directory

ls: cannot access '/dev/disk/by-id/': No such file or directory

ls: cannot access '/dev/disk/by-id/': No such file or directory

ls: cannot access '/dev/disk/by-id/': No such file or directory

ls: cannot access '/dev/disk/by-id/': No such file or directory

ls: cannot access '/dev/disk/by-id/': No such file or directory

ls: cannot access '/dev/disk/by-id/': No such file or directory

ls: cannot access '/dev/disk/by-id/': No such file or directory

ls: cannot access '/dev/disk/by-id/': No such file or directory

ls: cannot access '/dev/disk/by-id/': No such file or directory

ls: cannot access '/dev/disk/by-id/': No such file or directory

ls: cannot access '/dev/disk/by-id/': No such file or directory

ls: cannot access '/dev/disk/by-id/': No such file or directory

ls: cannot access '/dev/disk/by-id/': No such file or directory
```

**Comment by alikhanoitan** [comment]
@Patriciooo how to switch it off?

**Comment by Patriciooo** [comment]
> @Patriciooo how to switch it off?

In iCloud settings
<img width="515" alt="Captura de pantalla 2021-11-04 a las 17 56 13" src="https://user-images.githubusercontent.com/47217384/140384166-2b6766be-c624-4f77-ad9b-288d0567b603.png">
.

**Comment by blaise-io** [comment]
I consider private relay unlikely to be related as I believe it only applies to browsing with Safari.

Error 103 means that Ace Stream server cannot retrieve data for the stream. Most likely reason is zero peers or an invalid stream id.  

In the upcoming version of Ace Link I will give you more detail why the stream is not available. I'm also adding retrying the stream in case it takes a bit longer for the stream to have have data available.

**Comment by Patriciooo** [comment]
Private relay is in Safari, in system and in the network. I have pinhole and I don't need it. In the Apple support of private relay say it is not working fine with multiple connections. For me the problem is off. Sorry if you don't like.

**Comment by blaise-io** [comment]
You're right, I shouldn't have relied on a short marketing text which mentioned only Safari.

I did some testing with private relay in [a new version](https://github.com/blaise-io/acelink/files/7477417/Ace.Link.1.9.0-debug.dmg.zip) I'm working on. Private relay makes connecting to streams a lot slower and then seems to disable itself for Ace Link, but not for other apps. I will investigate more because this is weird.

Note that you may have to restart Ace Link after disabling private relay.

**Comment by tropxy** [comment]
I am also experiencing this issue :/

**Comment by blaise-io** [comment]
Anyone still having this issue on 2.0.5? 2.0.5 has more lenient timeouts and Apple may have changed private relay.

**Comment by Patriciooo** [comment]
2.0.3 and 2.0.4 are not working in M1/M2, but 2.0.5 is working fine. Thanks.
