### ISSUE TITLE
Stream stops after a few seconds with Operation not permitted error

### ISSUE THREAD

**Issue by haraldini** [blaise-io/acelink#41]
```
2021-12-12 01:20:05,924|AceStreamCoreThread|acestream.live.download.9aa78c43ac042c4d0919a9396c53e23ad8b4a41f|send_multicast_pex_announce: error

Traceback (most recent call last):

  File "core.c", line 1449, in 

  File "ACEStream/Core/APIImplementation/LiveDownloadImpl.py", line 594, in send_multicast

  File "ACEStream/Core/APIImplementation/LaunchManyCore.py", line 1162, in send_multicast

error: [Errno 1] Operation not permitted
```

**Comment by blaise-io** [comment]
Can you verify whether this issue sill exists on 2.0.0?

**Comment by blaise-io** [comment]
No timely response, please reopen if still an issue.
