### ISSUE TITLE
Error running Acelink Server

### ISSUE THREAD

**Issue by fernandonavarro1** [blaise-io/acelink#93]
I execute `docker run --platform=linux/amd64 --rm -p 6878:6878 blaiseio/acelink ` or `docker run --rm -p 6878:6878 blaiseio/acelink` but in both cases shows the same logs of error and I can't open the url `http://127.0.0.1:6878/ace/getstream?id=<acestream id>` in VLC

(3 months ago this worked for me)

**Additional debug info**  

2024-08-16 19:28:04,450|TrafficStatsSenderThread|acestream.TrafficStatsSender|init: error: HTTP Error 404: Not Found
2024-08-16 19:28:04,863|PlaylistTaskManagerThread-32|acestream.UpdateNotificationsTask|failed to update notifications
Traceback (most recent call last):
  File "/usr/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "ACEStream/Core/Utilities/timeouturlopen.py", line 279, in connect
OSError: failed to connect

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ACEStream/Core/Tasks/UpdateNotificationsTask.py", line 24, in run
  File "ACEStream/Core/notifications_v3/api.py", line 19, in get_notifications
  File "ACEStream/Core/Utilities/timeouturlopen.py", line 433, in urlOpenTimeout
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "ACEStream/Core/Utilities/timeouturlopen.py", line 283, in http_open
  File "/usr/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error failed to connect>
2024-08-16 19:28:07,154|ServiceTaskQueueThread-3|acestream.Session|sync_time: no response
2024-08-16 19:28:12,044|Thread-19|acestream.upnp|Unable to create Port Forward. Error: Success: <class 'Exception'>:Success

**Comment by svenkevs** [comment]
I have the same issue. Made sure docker pulled the image new. Is there any fix known?
